Use applied directives rather than directives by themselves
graphql-java/graphql-java-extended-validation pull request #72
Opened 2022-08-23 19:20 UTC by pelletier197

Update to use the new `AppliedDirectives` instead of the old `Directive`. 

This seems to break when upgrading to graphql-java 19, and it does still work for graphql-java 18.

2022-09-08 16:43 UTC, enriquedacostacambio approved these changes

2022-09-14 13:51 UTC, pelletier197 commented
@enriquedacostacambio any chance we can get this merged if it's okay? This is stopping us from updating to the latest GraphQL tools. 

Thanks in advance!

2022-09-15 03:56 UTC, bbakerman commented on src/main/java/graphql/validation/interpolation/ResourceBundleMessageInterpolator.java
> +import java.util.*;
This annoys me - please turn on expand all imports

2022-09-15 04:48 UTC, bbakerman requested changes
I am happy to accept this PR howev er I would really like it to not use `.*` imports on the changed files.

Could you please go back and re-format this please

2022-09-15 04:50 UTC, bbakerman commented
Ok progress over perfection - I will let this in and we can fix up the `.*` imports later - could I ask  that another PR be raised for that please @pelletier197

2022-09-15 04:50 UTC, merged

2022-09-15 10:43 UTC, pelletier197 commented
> Ok progress over perfection - I will let this in and we can fix up the `.*` imports later - could I ask that another PR be raised for that please @pelletier197

Yeah no problem, I'll do that today. Sorry about that, it's the default setting of Intellij and I didn't see it.